baseurl = "https://harishsr.gitlab.io/blog/"
contentdir    = "content"
layoutdir     = "layouts"
publishdir    = "public"
title = "Comp Notes"
canonifyurls  = true

DefaultContentLanguage = "en"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsUseClasses = true
pygmentCodeFences = true
#disqusShortname = "XXX"
#googleAnalytics = "XXX"

[Params]
  subtitle = "A blog of lessons I'm learning along my journey"
  logo = "img/linux.png"
  favicon = "img/linux.png"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = true
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Author]
  name = "Harish Ramachandran"
  email = "harishsr@icloud.com"
  gitlab = "harishsr"
  github = "harishsr"
  twitter = "harishsr"
  linkedin = "harishsr"
  stackoverflow = "users/3799287/harish-ramachandran"
  instagram = "harishsr.h"

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
    name = "About"
    url = "tags/about-me/"
    weight = 3

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 3
